---
- name: Install apache and start the service
  hosts: web
  tasks: 
    - name: Install required packages
      yum: 
        name: "{{ ansible_facts['ansible_local']['custom']['general']['packages'] }}"
        state: latest

    - name: Start and Enabled the service
      service:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['custom']['general']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['custom']['general']['enabled'] }}"
